---
- hosts: linux
  gather_facts: yes
  vars:
    var1: "{{ processName }}"
  tasks: 
    - name: Process Kill
      command: pkill "{{ var1 }}"
      when: ansible_os_family == "Debian" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'
      ignore_errors: yes
