---
- hosts: linux
  gather_facts: true
  vars:
    var1: "{{ com }}"
  tasks:
    - name: "RETRIEVE SNMP DISCOVERY INFORMATION"
      shell: snmpwalk -c "{{ var1 }}" -v2c "{{ target }}"
      become: true
      become_user: root
      become_method: sudo
      when: ansible_os_family == "Debian" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'
      register: result
    - name: "Output"
      debug: var=result.stdout_lines
      when: ansible_os_family == "Debian" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'
