---
- hosts: linux
  gather_facts: yes
  vars:
    var1: "{{ serviceName }}"
  tasks:
    - name: Service Start
      service: name={{ var1 }} state=started
      become: true
      become_user: root
      become_method: sudo
      ignore_errors: yes
      when: ansible_os_family == "Debian" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'
      register: result
    - name: Start Service Message
      debug: msg=" {{ var1 }} service has been started"
      when: ansible_os_family == "Debian" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'

