---
- name: Bootstrap Nodes
  hosts: router
  gather_facts: no
  connection: local
  tasks:
    - name: Collecting ARP Details
      ios_command:
        commands:
          - show arp
        provider: "{{ cli }}"
      register: running_config
    - debug: var=running_config.stdout_lines
