---
- hosts: linux
  gather_facts: yes
  tasks:
    - name: Set Warning Banner for Standard Login Services
      template: src=banner.j2 dest={{ item }} backup=yes
      changed_when: false
      with_items:
        -  /etc/motd
        - /etc/issue
        - /etc/issue.net