---
- hosts: windows
  gather_facts: true
  vars:
    var1: "{{ object }}"
  tasks:
    - name: Available Event Logs
      raw: Get-EventLog -List | Select Log
      when: (var1 == 'list') and (log is undefined) and (after is undefined) and (before is undefined) and (entrytype is undefined) and (source is undefined)
      register: result
    - debug: var=result.stdout_lines
      when: (var1 == 'list') and (log is undefined) and (after is undefined) and (before is undefined) and (entrytype is undefined) and (source is undefined)
    - name: List Logs
      raw: Get-EventLog -LogName {{ log }}
      when: (var1 == 'list') and (log is defined) and (after is undefined) and (before is undefined) and (entrytype is undefined) and (source is undefined)
      register: result
    - debug: var=result.stdout_lines
      when: (var1 == 'list') and (log is defined) and (after is undefined) and (before is undefined) and (entrytype is undefined) and (source is undefined)
    - name: List Logs
      raw: Get-EventLog -LogName {{ log }} -After "{{ after }}" -Before "{{ before }}"
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is undefined) and (source is undefined)
      register: result
    - debug: var=result.stdout_lines
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is undefined) and (source is undefined)
    - name: List Logs
      raw: Get-EventLog -LogName {{ log }} -After "{{ after }}" -Before "{{ before }}" -EntryType {{ entrytype }}
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is defined) and (source is undefined)
      register: result
    - debug: var=result.stdout_lines
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is defined) and (source is undefined)
    - name: List Logs
      raw: Get-EventLog -LogName {{ log }} -After "{{ after }}" -Before "{{ before }}" -EntryType {{ entrytype }} -Source {{ source }}
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is defined) and (source is defined)
      register: result
    - debug: var=result.stdout_lines
      when: (var1 == 'list') and (log is defined) and (after is defined) and (before is defined) and (entrytype is defined) and (source is defined)
