---
- hosts: windows
  gather_facts: no
  vars:
    mode: "{{ mode }}"
  tasks:
    - name: "Starting Service {{ svc_name }}"
      win_service: "name={{ svc_name }} state=started"
      when: mode == 'start'
    - debug: msg="Service has been Started"
      when: mode == 'start'
    - name: "Stopping Service {{ svc_name }}"
      win_service: "name={{ svc_name }} state=stopped"
      when: mode == 'stop'
    - debug: msg="Service has been Stopped"
      when: mode == 'stop'
    - name: "Restarting Service {{ svc_name }}"
      win_service: "name={{ svc_name }} state=restarted"
      when: mode == 'restart'
    - debug: msg="Service has been Restarted"
      when: mode == 'restart'
