---
- hosts: windows
  gather_facts: no
  vars:
   path: C:\Windows\Temp\Cleanup.out
  tasks:
    - name: Removing Cleanup File
      raw: 'CMD /C "DEL /F {{ path }} & DEL /F C:\Windows\Temp\Cleanup.bat"'
    - name: "Getting Disk(s) Details"
      raw: CMD /C "IF EXIST %SystemRoot%\SYSTEM32\cleanmgr.exe (wmic logicaldisk get size,freespace,caption /format:csv > C:\Windows\Temp\Cleanup.out & TYPE C:\Windows\Temp\Euo_StartDskClnupDtls.out & DEL C:\Windows\Temp\Cleanup.out) ELSE (echo FAILURE. Disk cleanup tool cannot be executed in this system.)"
      register: result
    - name: Output
      debug: var=result.stdout_lines
    - name: Copying Script
      win_copy: src=DiskCleanup777.bat dest=C:\Windows\Temp\Cleanup.bat
      when: result.stdout.find('FAILURE.') == -1
    - name: Starting Disk Cleanup
      raw: CMD /C "START "" /B C:\Windows\Temp\Cleanup.bat"
      when: result.stdout.find('FAILURE.') == -1
    - debug: msg="Disk cleanup process successfully started."
      when: result.stdout.find('FAILURE.') == -1
