---
- hosts: windows
  gather_facts: no
  vars:
   path: C:\Windows\Temp\Defrag.out
  tasks:
    - name: Remove Cleanup File
      raw: 'CMD /C "DEL /F {{ path }}"'
    - name: Copying Script
      win_copy: src=Defrag.bat dest=C:\Windows\Temp\Defrag.bat
    - name: Start Defrag Process
      raw: CMD /C "START "" /B C:\Windows\Temp\Defrag.bat {{ drive }}"
      register: result
    - debug: msg="Defrag process successfully started."
      when: result.stdout.find('FAILURE.') == -1

